### ISSUE TITLE
Create a logo for Chooj

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/chooj#11]
My idea is a `چ` inside brackets. something like:
```
[چ]
```

**Comment by strukturart** [comment]
@farooqkz  
https://github.com/strukturart/chooj-design/blob/main/logo.png # #

**Comment by farooqkz** [comment]
On the small screens of KaiOS phones and in app selection screen(read launcher) user will only see a black icon with a white thing on the corner.

**Comment by strukturart** [comment]
I think it's more of a startup screen than a launcher icon, if the style goes in the right direction, I can create one more.

**Comment by farooqkz** [comment]
One more thing, your design for Chooj is completely white/gray/black my Chooj's UI is actually colourful.

**Comment by strukturart** [comment]
therefore use css vars, then you can create color themes very quickly ;-)

**Comment by farooqkz** [comment]
![chooj](https://user-images.githubusercontent.com/15038218/166102475-3c63c5db-d3e8-4d1f-9298-13110db9235b.png)

how about this?

**Comment by farooqkz** [comment]
chooj has a logo now
