### ISSUE TITLE
Paginate between events

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/chooj#40]
Currently only the latest 8 events are shown. The ability to paginate between events is essential.

**Comment by minhduc-bui1** [comment]
This is a bit buggy: if you scroll up too much (3 - 4 pages) you'll get stuck at the top of that page

**Comment by farooqkz** [comment]
are you sure you are not reaching the beginning of the room's timeline?

**Comment by farooqkz** [comment]
I've realized that this overlap newly happens and I don't know why, yet.
