### ISSUE TITLE
Seen/unseen indicator

### ISSUE THREAD

**Issue by iGameEveryDay6** [farooqkz/chooj#44]
If u ask me that's among one of the most essential features u should add.

**Comment by farooqkz** [comment]
Can you explain more? I think you are talking about `last seen 2 days ago` indicator right?

**Comment by iGameEveryDay6** [comment]
Someting like this 
![image](https://user-images.githubusercontent.com/83013894/166494749-53eed0c2-e7d7-4296-91f9-fd56f047030f.png)
or this (in matrix)
![image](https://user-images.githubusercontent.com/83013894/166494970-cea8defd-19c6-4090-b473-1a9f5ce3ad6f.png)

**Comment by farooqkz** [comment]
closing as it's duplicate of #50
