### ISSUE TITLE
more explanations are needed for matrix newbies

### ISSUE THREAD

**Issue by strukturart** [farooqkz/chooj#47]
in the kaios discord server, the question often arises how the login works, i would find it useful if you could explain that in the readme file.

- where to create a matrix account
- explain the parameters of the login form
- how to make qr code for login

`PASS [homeserver] [homerserver url] [username] [password]
`

**Comment by farooqkz** [comment]
I've written what is pattern of QR code. Regarding the other stuff I think it is a good idea to add them to the client. But definitly not for `0.0.0`
