### ISSUE TITLE
Login does not work with split Matrix Domain/Homeserver Domain configurations

### ISSUE THREAD

**Issue by Syonyk** [farooqkz/chooj#5]
I'm able to log into my matrix.org account, but I can't log into my personal domain account - it seems the issue is that the login flow assumes that the homeserver URL is the same as the matrix ID URL.

https://github.com/farooqkz/chooj/blob/master/src/Login.js#L34

If your IDs are example.com domains (@user:example.com), but the actual server is matrix.example.org, this does not work.

An extra field to set these separately (defaulting to using the same) would enable logging into this supported configuration.

Thanks for all the work on this - excited to see KaiOS get a proper Matrix client!

**Comment by farooqkz** [comment]
How about an extra field for userID? e.g. `@farooqkz:mozilla.org`

**Comment by Syonyk** [comment]
I tried this and it let me log in:

```
diff --git a/src/Login.js b/src/Login.js
index 7191580..1d0ac7b 100644
--- a/src/Login.js
+++ b/src/Login.js
@@ -31,7 +31,7 @@ class Login extends Component {
       case "m.login.password":
         window.mClient
           .loginWithPassword(
-            `@${this.username}:${this.homeserverUrl.replace("https://", "")}`,
+            `@${this.username}:${this.homeserverDomain.replace("https://", "")}`,
             this.password
           )
           .then((result) => {
@@ -107,6 +107,7 @@ class Login extends Component {
     this.loginFlows = [];
     this.selectedLoginFlow = "";
     this.homeserverUrl = "";
+    this.homeserverDomain = "";
     this.username = "";
     this.password = "";
     this.state = {
@@ -127,6 +128,13 @@ class Login extends Component {
             },
             label: "Homeserver URL",
           },
+          {
+            placeholder: "example.com",
+            onChange: (value) => {
+              this.homeserverDomain = value;
+            },
+            label: "Homeserver Domain",
+          },
           {
             placeholder: "mrpotato",
             onChange: (value) => {
```

However, there are also some issues when there are no rooms created - I didn't save off the errors, but if you log into a fresh account, it complains about one of the rooms variables not existing, and won't get past the cow (you have to look at the debug logs in the webide).  You can work around it, but try logging into a blank account and you'll see the problem.

**Comment by farooqkz** [comment]
Thank you for the workaround. For that other issue(empty room thing), please open another issue so that it will be easier for us to track stuff :)

**Comment by farooqkz** [comment]
@Syonyk The issue must have been solved in new commits. Please check and if it's okay, close this issue.

**Comment by Syonyk** [comment]
This seems to work!  Now to figure out why my rooms are black and I can't read anything...

**Comment by farooqkz** [comment]
> This seems to work! Now to figure out why my rooms are black and I can't read anything...

Please open another issue for that. Include steps to reproduce, the device and the commit which you've tried.
