### ISSUE TITLE
Move UI components into a separate library

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/chooj#62]
A lot of components which chooj uses are from [KaiUI by AdrianMachado](https://github.com/AdrianMachado/KaiUI). chooj has it as its dependency but uses only styling stuff from that repo and I've implemented components for Inferno myself.

Currently, all the project is under GPLv3 including the UI components. I think it is a good idea to create a separate KaiUI repository with only stylings from this KaiUI and another repository which depends on this one and that uses those stylings in Inferno.

There are manyladvantages:

1. As the KaiUI from Adrian is not updated anymore, other KaiOS developers and I could take control of it and maintain it.
2. Other developers could use the new KaiUI library for their projects without having to include all dependencies from Adrian's KaiUI. I guess only `node-sass` will be needed.
3. Other developers could create framework-specific UI libraries based on this with whatever licencing.

**Comment by farooqkz** [comment]
For the repo without React components and just styles, a friend has created this: https://github.com/cyan-2048/KaiUI-no-deps

However, nothing has been done other than removing ALL dependencies.

@Cyan-2048, Are you willing to take care of that?

**Comment by cyan-2048** [comment]
@farooqkz  i have only created the repo for a quick a dirty fix for something I was creating... I have no plans on improving it or even using it....

**Comment by farooqkz** [comment]
Finally it is done. Thanks to Simon Laux :)
