### ISSUE TITLE
Jabber/XMPP

### ISSUE THREAD

**Issue by sjehuda** [farooqkz/chooj#63]
Please add support for XMPP

XMPP libraries
https://strophe.im/strophejs/
https://github.com/xmppjs

**Comment by farooqkz** [comment]
Hello. This is a client for Matrix not XMPP.

**Comment by sjehuda** [comment]
I figured it's relevant.

yaxim, a messenger for Android, supports XMPP and Matrix.

Anyhow, there's an XMPP project for KaiOS at https://git.disroot.org/badrihippo/convo

**Comment by farooqkz** [comment]
hmm interesting. But there is no enough manpower to even create a useful Matrix client...

**Comment by sjehuda** [comment]
In case you'll be interested, please let me know and I hope I'll be
able to help with development.

Thank you

**Comment by farooqkz** [comment]
Since there is another effort for a XMPP client, I don't think I would add XMPP support to chooj.
