### ISSUE TITLE
Missing manifest.webapp?

### ISSUE THREAD

**Issue by izissise** [farooqkz/chooj#65]
Hello, I just compiled chooj but I don't see any manifest.webapp in the build folder.
I tried creating one but then on the Login info screen after I enter my info and press next I get this error: 
![Screenshot_20230118_223850](https://user-images.githubusercontent.com/2104672/213300593-d00d837e-8eb3-4729-abea-b0c7ebd29266.png)

**Comment by farooqkz** [comment]
Hello. I'm changing the build system to parcel and I'm not done yet.

**Comment by farooqkz** [comment]
Fixed

**Comment by izissise** [comment]
Thanks a lot :)
