### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/chooj#67]
Currently, parcel is the build system chooj uses. When targeting FF48, parcel tries to create a bundle which works on FF48 newer browsers. FF48 does not support JS modules but most newer browsers do. So parcel creates two sets of JS assets for module and nomodule. And the module JS assets never get used in KaiOS 2.x.

Related issue:

https://github.com/parcel-bundler/parcel/issues/8783

**Comment by Simon-Laux** [comment]
maybe just add a small script that removes the html tag and the file "manually" from the bundle, that way we would not need wait for any solutions from parcel.
