### ISSUE TITLE
Indicate if the message hasn't been sent, yet

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/chooj#80]
When a message is sent by the user, it takes some time till the server receives the message. It would be nice if chooj was telling the user somehow that the message still is not sent. Maybe an animation which turns text color from red to black and vice versa?

**Comment by strukturart** [comment]
how about one of these css animations: https://cssloaders.github.io/

**Comment by farooqkz** [comment]
> how about one of these css animations: https://cssloaders.github.io/

These suit loading others' messages. This issue is about message sent by users themselves.
