### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/chooj#81]
- [x] ChatRoomItem
 - [x] ChatDMItem
 - [x] CallScreen
 - [x] About
 - [x] ChatTextInput
 - [x] ImageViewer
 - [x] DMsView
 - [x] RoomsView
 - [x] RoomView
 - [x] Login
 - [x] LoginWithQr
 - [x] InvitesView
 - [x] Waiting
 - [x] VoiceInput
 - [x] Settings
 - [x] MessageItems
 - [x] Matrix
 - [x] sw.js

**Comment by farooqkz** [comment]
The migration is almost complete. However, there are many things:

 1. Typescript does not recognize KaiOS specific stuff like `MozActivity` and `navigator.volumeManager`. The long term workaround is having types defined for them. But what is the short term workaround? Related issue: https://github.com/microsoft/TypeScript/issues/35402
 2. `check` command includes stuff from `node_modules` too. What is the workaround for this? (Run `yarn run check`)
 3. Regarding #83 I have done it. But it makes the code ugly to check everytime for `mClient` being non-null. Do `grep 'if (!shared.mClient`

ping @Cyan-2048 @Simon-Laux

**Comment by Simon-Laux** [comment]
> But what is the short term workaround?

define a `todo` type you can search for: `type todo = any`.

> 2. check command includes stuff from node_modules too. What is the workaround for this? (Run yarn run check)

I don't understand what the problem is, please elaborate.

> Regarding https://github.com/farooqkz/chooj/issues/83 I have done it. But it makes the code ugly to check everytime for mClient being non-null. Do grep 'if (!shared.mClient'

can the matrix client become undefined? or is this only about startup?

you could have a getter function that has the check:
```
class Shared {
_matrixClient: MatrixClientType | null = null
get matrixClient(): MatrixClientType {
 if(matrixClient === null) {
  throw new Error("matrix client is undefined, this should not happen! Is the app still starting up and the devs forgot a check?")
 }
 return _matrixClient
}
}
```
sure that is an extra if statement that gets run every time, but if you can not build the app in a way that you can be sure it's set you at least have the error message when there is a bug and it is really not set.

**Comment by farooqkz** [comment]
Thank you Simon for the 3rd thing. Regarding the 1st, can you please elaborate? And regarding the 2nd:

```
Errors  Files
     5  node_modules/matrix-js-sdk/src/ReEmitter.ts:77
     4  node_modules/matrix-js-sdk/src/autodiscovery.ts:454
    21  node_modules/matrix-js-sdk/src/client.ts:274
     8  node_modules/matrix-js-sdk/src/crypto/CrossSigning.ts:21
     1  node_modules/matrix-js-sdk/src/crypto/EncryptionSetup.ts:308
    14  node_modules/matrix-js-sdk/src/crypto/OlmDevice.ts:17
     3  node_modules/matrix-js-sdk/src/crypto/OutgoingRoomKeyRequestManager.ts:17
     1  node_modules/matrix-js-sdk/src/crypto/SecretSharing.ts:16
    10  node_modules/matrix-js-sdk/src/crypto/algorithms/base.ts:89
     6  node_modules/matrix-js-sdk/src/crypto/algorithms/megolm.ts:21
     2  node_modules/matrix-js-sdk/src/crypto/algorithms/olm.ts:72
     5  node_modules/matrix-js-sdk/src/crypto/backup.ts:609
     7  node_modules/matrix-js-sdk/src/crypto/crypto.ts:19
     9  node_modules/matrix-js-sdk/src/crypto/dehydration.ts:17
    17  node_modules/matrix-js-sdk/src/crypto/index.ts:20
     2  node_modules/matrix-js-sdk/src/crypto/key_passphrase.ts:39
     7  node_modules/matrix-js-sdk/src/crypto/olmlib.ts:21
     3  node_modules/matrix-js-sdk/src/crypto/recoverykey.ts:24
     1  node_modules/matrix-js-sdk/src/crypto/store/indexeddb-crypto-store.ts:150
    21  node_modules/matrix-js-sdk/src/crypto/store/localStorage-crypto-store.ts:81
    22  node_modules/matrix-js-sdk/src/crypto/store/memory-crypto-store.ts:265
     2  node_modules/matrix-js-sdk/src/crypto/verification/Base.ts:63
    14  node_modules/matrix-js-sdk/src/crypto/verification/QRCode.ts:158
     6  node_modules/matrix-js-sdk/src/crypto/verification/SAS.ts:21
     4  node_modules/matrix-js-sdk/src/crypto/verification/request/InRoomChannel.ts:53
     2  node_modules/matrix-js-sdk/src/crypto/verification/request/ToDeviceChannel.ts:301
     2  node_modules/matrix-js-sdk/src/crypto/verification/request/VerificationRequest.ts:135
     2  node_modules/matrix-js-sdk/src/http-api/fetch.ts:58
     4  node_modules/matrix-js-sdk/src/http-api/index.ts:63
     1  node_modules/matrix-js-sdk/src/http-api/interface.ts:20
     1  node_modules/matrix-js-sdk/src/http-api/utils.ts:17
     1  node_modules/matrix-js-sdk/src/interactive-auth.ts:277
     2  node_modules/matrix-js-sdk/src/logger.ts:33
     1  node_modules/matrix-js-sdk/src/matrix.ts:107
     3  node_modules/matrix-js-sdk/src/models/event.ts:1433
     2  node_modules/matrix-js-sdk/src/models/room-member.ts:325
     1  node_modules/matrix-js-sdk/src/models/room-summary.ts:43
     5  node_modules/matrix-js-sdk/src/models/room.ts:545
     3  node_modules/matrix-js-sdk/src/models/thread.ts:523
     3  node_modules/matrix-js-sdk/src/models/typed-event-emitter.ts:105
     1  node_modules/matrix-js-sdk/src/pushprocessor.ts:467
     6  node_modules/matrix-js-sdk/src/realtime-callbacks.ts:37
     8  node_modules/matrix-js-sdk/src/rust-crypto/rust-crypto.ts:159
     1  node_modules/matrix-js-sdk/src/scheduler.ts:54
     2  node_modules/matrix-js-sdk/src/sliding-sync-sdk.ts:522
     1  node_modules/matrix-js-sdk/src/store/indexeddb-local-backend.ts:119
    10  node_modules/matrix-js-sdk/src/store/memory.ts:115
    28  node_modules/matrix-js-sdk/src/store/stub.ts:62
     7  node_modules/matrix-js-sdk/src/sync.ts:724
     2  node_modules/matrix-js-sdk/src/timeline-window.ts:295
    12  node_modules/matrix-js-sdk/src/utils.ts:102
     8  node_modules/matrix-js-sdk/src/webrtc/call.ts:24
     3  node_modules/matrix-js-sdk/src/webrtc/groupCall.ts:273
     2  node_modules/matrix-js-sdk/src/webrtc/mediaHandler.ts:424
     3  node_modules/matrix-js-sdk/src/webrtc/stats/callStatsReportGatherer.ts:98
     3  node_modules/matrix-js-sdk/src/webrtc/stats/media/mediaSsrcHandler.ts:17
     1  node_modules/matrix-js-sdk/src/webrtc/stats/trackStatsBuilder.ts:43
     2  node_modules/matrix-js-sdk/src/webrtc/stats/transportStatsBuilder.ts:10
     5  src/About.tsx:3
     1  src/App.tsx:36
    22  src/CallScreen/CallScreen.tsx:3
     6  src/ChatDMItem.tsx:2
     2  src/ChatRoomItem.tsx:3
     1  src/ChatTextInput/ChatTextInput.tsx:11
     4  src/DMsView.tsx:3
     5  src/Login.tsx:5
     1  src/LoginWithQR/LoginWithQR.tsx:8
     5  src/Matrix.tsx:7
     8  src/RoomView/RoomView.tsx:3
     1  src/RoomsView.tsx:2
error Command failed with exit code 2.
```

This is tail of output of `yarn run check` which basically runs `tsc -p ./tsconfig.json --noEmit`

**Comment by Simon-Laux** [comment]
regarding the 1. thing: I suggested to use a alias type named "todo" so you basically use `any` but have an easy way to search for those places to properly type them later.

regarding 2. we need to modify `tsconfig.json`, I'd try adding `node_modules` to the `exclude` array.

**Comment by farooqkz** [comment]
> regarding the 1. thing: I suggested to use a alias type named "todo" so you basically use `any` but have an easy way to search for the places where you used it, to properly type them later.
> 
> regarding 2. we need to modify `tsconfig.json`, I'd try adding `node_modules` to the `exclude` array.

Thank you. Regarding 2, I have done so but with no luck. Furthermore, I have included some stuff directly from `matrix-js-sdk` files. Could it be source of the problem?

**Comment by farooqkz** [comment]
There is another problem:

```
src/RoomsView.tsx:2:10 - error TS2614: Module '"KaiUI"' has no exported member 'ListViewKeyed'. Did you mean to use 'import ListViewKeyed from "KaiUI"' instead?

2 import { ListViewKeyed } from "KaiUI";
           ~~~~~~~~~~~~~
```

The app compiles fine tho. But there is a problem with `tsc` checking stuff.

**Comment by Simon-Laux** [comment]
looks like there is no way to ignore the errors inside of matrix-js-sdk... :( (https://github.com/microsoft/TypeScript/issues/40426)
