### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Boris55555** [farooqkz/chooj#82]
Cannot login. Using Nokia 8110 4G. When typing server and username the next button don't work.

**Comment by farooqkz** [comment]
> Cannot login. Using Nokia 8110 4G. When typing server and username the next button don't work.

1. Are you sure you've got a connection to your homeserver?
2. How are you typing your Matrix ID? It must be in the form of `@username:homeserver.tld`
3. Can you post console logs?

**Comment by Boris55555** [comment]
Yes, I can connect from desktop element and android element etc.
I tried also that form and using QR code, but no success.
I can try to get some logs.

**Comment by Boris55555** [comment]
undefined: fetch failed: NetworkError when attempting to fetch resource.
Stack trace:
$09d90a79e08ccc1f$var$ConnectionError@app://chooj.bananahackers.net/index.512e15ce.js:29379:9
requestOtherUrl/</<@app://chooj.bananahackers.net/index.512e15ce.js:29213:31
step@app://chooj.bananahackers.net/index.512e15ce.js:1566:18
$5dbeebf3270b2dc0$export$67ebef60e6f28a6/verb/<@app://chooj.bananahackers.net/index.512e15ce.js:1507:20
$7763d6aaa8033263$var$asyncGeneratorStep@app://chooj.bananahackers.net/index.512e15ce.js:1297:20
_throw@app://chooj.bananahackers.net/index.512e15ce.js:1315:17
callReaction@app://chooj.bananahackers.net/index.512e15ce.js:110505:26
notify/<@app://chooj.bananahackers.net/index.512e15ce.js:110526:42
flush@app://chooj.bananahackers.net/index.512e15ce.js:110302:13
  
index.512e15ce.js:137235:43
undefined: fetch failed: NetworkError when attempting to fetch resource.
Stack trace:
$09d90a79e08ccc1f$var$ConnectionError@app://chooj.bananahackers.net/index.512e15ce.js:29379:9
requestOtherUrl/</<@app://chooj.bananahackers.net/index.512e15ce.js:29213:31
step@app://chooj.bananahackers.net/index.512e15ce.js:1566:18
$5dbeebf3270b2dc0$export$67ebef60e6f28a6/verb/<@app://chooj.bananahackers.net/index.512e15ce.js:1507:20
$7763d6aaa8033263$var$asyncGeneratorStep@app://chooj.bananahackers.net/index.512e15ce.js:1297:20
_throw@app://chooj.bananahackers.net/index.512e15ce.js:1315:17
callReaction@app://chooj.bananahackers.net/index.512e15ce.js:110505:26
notify/<@app://chooj.bananahackers.net/index.512e15ce.js:110526:42
flush@app://chooj.bananahackers.net/index.512e15ce.js:110302:13
  

Stack trace:
$09d90a79e08ccc1f$var$ConnectionError@app://chooj.bananahackers.net/index.512e15ce.js:29379:9
requestOtherUrl/</<@app://chooj.bananahackers.net/index.512e15ce.js:29213:31
step@app://chooj.bananahackers.net/index.512e15ce.js:1566:18
$5dbeebf3270b2dc0$export$67ebef60e6f28a6/verb/<@app://chooj.bananahackers.net/index.512e15ce.js:1507:20
$7763d6aaa8033263$var$asyncGeneratorStep@app://chooj.bananahackers.net/index.512e15ce.js:1297:20
_throw@app://chooj.bananahackers.net/index.512e15ce.js:1315:17
callReaction@app://chooj.bananahackers.net/index.512e15ce.js:110505:26
notify/<@app://chooj.bananahackers.net/index.512e15ce.js:110526:42
flush@app://chooj.bananahackers.net/index.512e15ce.js:110302:13
  
index.512e15ce.js:137235:43
undefined: fetch failed: NetworkError when attempting to fetch resource.
Stack trace:
$09d90a79e08ccc1f$var$ConnectionError@app://chooj.bananahackers.net/index.512e15ce.js:29379:9
requestOtherUrl/</<@app://chooj.bananahackers.net/index.512e15ce.js:29213:31
step@app://chooj.bananahackers.net/index.512e15ce.js:1566:18
$5dbeebf3270b2dc0$export$67ebef60e6f28a6/verb/<@app://chooj.bananahackers.net/index.512e15ce.js:1507:20
$7763d6aaa8033263$var$asyncGeneratorStep@app://chooj.bananahackers.net/index.512e15ce.js:1297:20
_throw@app://chooj.bananahackers.net/index.512e15ce.js:1315:17
callReaction@app://chooj.bananahackers.net/index.512e15ce.js:110505:26
notify/<@app://chooj.bananahackers.net/index.512e15ce.js:110526:42
flush@app://chooj.bananahackers.net/index.512e15ce.js:110302:13
  
index.512e15ce.js:137235:43
undefined: fetch failed: NetworkError when attempting to fetch resource.
Stack trace:
$09d90a79e08ccc1f$var$ConnectionError@app://chooj.bananahackers.net/index.512e15ce.js:29379:9
requestOtherUrl/</<@app://chooj.bananahackers.net/index.512e15ce.js:29213:31
step@app://chooj.bananahackers.net/index.512e15ce.js:1566:18
$5dbeebf3270b2dc0$export$67ebef60e6f28a6/verb/<@app://chooj.bananahackers.net/index.512e15ce.js:1507:20
$7763d6aaa8033263$var$asyncGeneratorStep@app://chooj.bananahackers.net/index.512e15ce.js:1297:20
_throw@app://chooj.bananahackers.net/index.512e15ce.js:1315:17
callReaction@app://chooj.bananahackers.net/index.512e15ce.js:110505:26
notify/<@app://chooj.bananahackers.net/index.512e15ce.js:110526:42
flush@app://chooj.bananahackers.net/index.512e15ce.js:110302:13
  
index.512e15ce.js:137235:43
undefined: fetch failed: NetworkError when attempting to fetch resource.
Stack trace:
$09d90a79e08ccc1f$var$ConnectionError@app://chooj.bananahackers.net/index.512e15ce.js:29379:9
requestOtherUrl/</<@app://chooj.bananahackers.net/index.512e15ce.js:29213:31
step@app://chooj.bananahackers.net/index.512e15ce.js:1566:18
$5dbeebf3270b2dc0$export$67ebef60e6f28a6/verb/<@app://chooj.bananahackers.net/index.512e15ce.js:1507:20
$7763d6aaa8033263$var$asyncGeneratorStep@app://chooj.bananahackers.net/index.512e15ce.js:1297:20
_throw@app://chooj.bananahackers.net/index.512e15ce.js:1315:17
callReaction@app://chooj.bananahackers.net/index.512e15ce.js:110505:26
notify/<@app://chooj.bananahackers.net/index.512e15ce.js:110526:42
flush@app://chooj.bananahackers.net/index.512e15ce.js:110302:13

**Comment by StephanStanisic** [comment]
I seem to have the same issue, both using the prepacked app from https://store.bananahackers.net/ and installing a freshly build one from master. I also tried using both qr-code and the form, but both didn't work. I also get `NetworkError when attempting to fetch resource` in the console.

**Comment by farooqkz** [comment]
> I seem to have the same issue, both using the prepacked app from https://store.bananahackers.net/ and installing a freshly build one from master. I also tried using both qr-code and the form, but both didn't work. I also get `NetworkError when attempting to fetch resource` in the console.

Thanks for your confirmation. However, it will take some time till I finish my current projects and come back to chooj.

**Comment by Boris55555** [comment]
> @StephanStanisic @Boris55555
> 
> Hello. Please test this build:
> 
> https://farooqkz.de1.hashbang.sh/matrix-client-builds/03b4d0adc5ac9e2c615d7b0a0e582ced7dc96b7d.zip

Thanks. I tested it today and it works. Even got a notification on the Nokia 8110 4G for a new message.

**Comment by farooqkz** [comment]
> > @StephanStanisic @Boris55555
> > Hello. Please test this build:
> > https://farooqkz.de1.hashbang.sh/matrix-client-builds/03b4d0adc5ac9e2c615d7b0a0e582ced7dc96b7d.zip
> 
> Thanks. I tested it today and it works. Even got a notification on the Nokia 8110 4G for a new message.

Nice. Remember that the notifications are experimental and not reliable. For the next steps you can consider:

 - Donating to the project to help it. Even small amounts are good.
 - Joining chooj's room
 - Getting another KaiOS device as the BananaPhone is known for its crappy keypad.
