### ISSUE TITLE
avoid relying on window for shared objects

### ISSUE THREAD

**Issue by cyan-2048** [farooqkz/chooj#83]
currently (05/16/23), there are 12 files that has the code `window.mClient`
this is very problematic as this project plans on converting to TypeScript (#81)

assigning objects to window is never liked in TypeScript
![image](https://github.com/farooqkz/chooj/assets/72785466/c05893b2-e9a0-4f9c-bfd7-81f514f7dc26)

### create a shared.js file
create a shared.js file that will contain shared objects
```JS
export let mClient = {};
export let isFullscreen = false;
export let states = new Map();

// other files
import { mClient } from "./shared.js";

// if exposing to window is really necessary
import * as shared from "./shared.js";
Object.assign(window, { shared })
```
this not only satisfies TypeScript, it would even make code be more compact!

### create a declaration
```TS
declare global {
  var mClient: {};
  // ...
}
```

**Comment by farooqkz** [comment]
Thank you my friend!

**Comment by farooqkz** [comment]
@cyan-2048 I am converting to TS now and I want to implement it as well as you said, TS doesn't like assigning to `window`. So from what I understand, I should declare stuff in a `shared.js` file and declare stuff there. then import them in every file needed? What is that last part `declare global`?

ping @Simon-Laux need advice from you as well please :)

**Comment by cyan-2048** [comment]
> @cyan-2048 I am converting to TS now and I want to implement it as well as you said, TS doesn't like assigning to `window`. So from what I understand, I should declare stuff in a `shared.js` file and declare stuff there. then import them in every file needed? What is that last part `declare global`?
> 
> ping @Simon-Laux need advice from you as well please :)

You're supposed to put the declare thing in a d.ts file... But the shared.js thing is probably better...

**Comment by cyan-2048** [comment]
Also, importing `let isFullscreen;` and changing the value probably wouldn't work... probably making an object that has the state would probably work...
so instead of isFullscreen being a boolean...
`export let isFullscreen = { value: true };`
And just mutate that object.

**Comment by farooqkz** [comment]
mutate a `const`? 

 PS: @cyan-2048 can you do review once i finish the convert?

**Comment by cyan-2048** [comment]
> mutate a `const`? 
> 
>  PS: @cyan-2048 can you do review once i finish the convert?

Yes you can "mutate" an object declared by `const`, because you're not redeclaring the object.

**Comment by cyan-2048** [comment]
> mutate a `const`? 
> 
>  PS: @cyan-2048 can you do review once i finish the convert?

Yes you can "mutate" an object declared by `const`, because you're not redeclaring the object.

**Comment by Simon-Laux** [comment]
you need Object.freeze() if you want to prevent modification of it.

**Comment by cyan-2048** [comment]
> mutate a `const`? 
> 
>  PS: @cyan-2048 can you do review once i finish the convert?

A review is possible, just ping me in discord👀
